apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-test
  annotations: 
    changeCause: "hello world"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-service-test-pods
  template:
    metadata:
      labels:
        app: metadata-service-test-pods
    spec:
      containers:
        - name: metadata-service-test
          image: sunitparekh/metadata:v2.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          env:
          - name: MONGODB_URI
            value: mongodb://mongosvc/metadata
            name: API_VERSION
            value: "v1"