apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo-db-depl
          image: mongo
          ports:
            - containerPort: 27017


