apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-db-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo-db-test
          image: mongo
          ports:
            - containerPort: 27017