apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadata-service-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-service-test-pods
  template:
    metadata:
      labels:
        app: metadata-service-test-pods
    spec:
      containers:
        - name: metadata-service-test
          image: sunitparekh/metadata:v1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3


