apiVersion: v1
kind: Service
metadata: 
  name: metadata-svc-np
spec:
  type: NodePort
  selector:
    app: metadata-service-test-pods
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30003