apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
spec:
  volumes:
    - name: public
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: mongo-db
      image: mongo
      ports:
        - containerPort: 27017
          name: "mongo"
      volumeMounts:
        - mountPath: "data/db"
          name: public